generic:
  skip_lines: 0
  col_sep: ','
  clean_rows: true
  multiple_files: false
  liberal_parsing: false

CipCode:
  liberal_parsing: true

EightKey:
  skip_lines: 1

Mou:
  skip_lines: 1

Hcm:
  skip_lines: 2

Complaint:
  skip_lines: 7

Program:
  col_sep: '|'

SchoolCertifyingOfficial:
  liberal_parsing: true

VrrapProvider:
  clean_rows: false

CensusLatLong:
  multiple_files: true
  no_headers: true
